services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quick_link_app
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${PORT}:3333"
    depends_on:
      - mongo
  mongo:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: {}
